# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
For the most part it should work because the logic of the code is right, the calling of the function is also provided the augment but it's might need a  `try/catch` be actually safe?

# Teacher Feedback

This code will work and completely execute but should it? 

Score: 2/3